# This is an example config file. It cannot be used directly.
# Copy this file to the project root as config.yml and make the changes necessary for your environment.
# If you omit a sink, it will not be loaded.
source:
  opcua:
    endpoint: "opc.tcp://milo.digitalpetri.com:62541/milo"
    username:
    password:
    clientid: "opcua2sink"
    sampleratems: 2000
    # Here you define the OPCUA Tags you want to subscribe to, and the sinks you want them to go to
    subscriptions:
      # This is a simple subscription that logs a tag value to a text file
      - nodeid: "ns=0;i=2265"
        label: "Build Number"
        sink: "log2csv"
      # This is a complex subscription that reads a tag value sends it to multiple sinks
      # Since there are an array of sinks, there is also an array of sinkparams
      #   The first empty string means no param is needed
      #   The second string is the command for the second sink: a database insert
      #   The third sinkparam is an ID used for a mutation into the CESMII SMIP/ThinkIQ
      - topic: "ns=2;s=Dynamic/RandomFloat"
        label: "Random Number"
        sink: ["log2csv", "mysqlsink", "smipgraphql"]
        sinkparam: ["","insert into tag_samples (timestamp, value, label) values (%s, %s, %s)", 145402]
# Each sink is a place that data can go. Each will have its own configuration needs.
sinks:
  log2csv:
    path: "./opc_log.csv"
    maxsize: 2000000
    flushonmax: True
  mysqlsink:
    host: "localhost"
    database: "YOURDB"
    user: "YOURDBUSER"
    password: "YOURDBPASSWORD"
  smip:
    url: "https://<YOURINSTANCE>.cesmii.net/graphql"
    authenticator: "YOUR AUTHENTICATOR"
    role: "<YOUR>_group"
    password: "YOUR AUTHENTICATOR PASSWORD"
    username: "YOUR USERNAME"
    batchuntil: 10